name: Build package / publish

on:
  pull_request:  # Check that package can be built even on PRs
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ "v*" ]
  release:
    types: [ published ]

jobs:
  publish:
    uses: iiasa/actions/.github/workflows/publish.yaml@pypi-trusted
    environment: release
    permissions:
      id-token: write
